# Generated by Django 4.0.1 on 2022-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_brithdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=50, verbose_name='Familiyasi')),
                ('tel_number', models.PositiveIntegerField(verbose_name='telfon')),
            ],
        ),
    ]
