# Generated by Django 3.2.8 on 2021-12-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Gellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='izoh')),
                ('image', models.ImageField(upload_to='gellary/', verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='report_images', verbose_name='Rasmi')),
                ('description', models.TextField(verbose_name='Qoshimcha')),
                ('date', models.DateField(auto_now_add=True, verbose_name='sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Rasmi')),
                ('body', models.TextField(verbose_name='Matni')),
                ('date', models.DateField(auto_now_add=True, verbose_name='sanasi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='teachers.teacher')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.category')),
                ('gellary', models.ManyToManyField(related_name='gnews', to='main.Gellary')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=50, verbose_name='Familiya')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.news')),
            ],
        ),
    ]
