# Generated by Django 3.2.8 on 2021-12-30 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('tel_number', models.CharField(max_length=50, verbose_name='tel_number')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Video'),
            preserve_default=False,
        ),
    ]
