# Generated by Django 3.2.8 on 2021-12-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211230_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellary',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='izoh'),
        ),
        migrations.AlterField(
            model_name='news',
            name='gellary',
            field=models.ManyToManyField(blank=True, related_name='gnews', to='main.Gellary'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, max_length=60, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='description',
            field=models.TextField(blank=True, verbose_name='Qoshimcha'),
        ),
    ]
